### NumPy is a fundamental package for scientific computing in Python, and it provides support for working with arrays and matrices.
#### Ndarrays (n-dimensional arrays):
#### NumPy's main data structure is the ndarray, short for n-dimensional array. It is a versatile and efficient array object that can hold elements of the same data type. Ndarrays can have any number of dimensions, allowing you to represent scalars, vectors, matrices, and more complex data structures.

In [1]:
import numpy as np

In [2]:
# Create a 1-dimensional array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [3]:
# Create a 2-dimensional array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


### Basic operations with Ndarrays:
#### NumPy allows you to perform various mathematical and logical operations on ndarrays efficiently. Here are some basic operations:

In [17]:
# Arithmetic Operations

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
addition = a + b
print("Addition : ", addition)

# Element-wise subtraction
subtraction = a - b
print("Subtraction : ", subtraction)

# Element-wise multiplication
multiplication = a * b
print("multiplication", multiplication)

# Element-wise division
division = a / b
print("division", division)

Addition :  [5 7 9]
Subtraction :  [-3 -3 -3]
multiplication [ 4 10 18]
division [0.25 0.4  0.5 ]


### Array Broadcasting:
#### NumPy performs automatic broadcasting when you perform operations on arrays of different shapes. It allows you to work with arrays that may not have the exact same dimensions.

In [21]:
c = np.array([2, 2, 2])

result = 5 + c  # Broadcasting: [1+2, 2+2, 3+2]
print("result : " ,result)

result :  [7 7 7]


In [11]:
# Square the elements of a list
c = np.array([2, 4, 5, 6])

result = c ** 2 # Broadcasting: [1+2, 2+2, 3+2]
print("result : " ,result)

result :  [ 4 16 25 36]


### Universal Functions (ufuncs):
#### NumPy provides a wide range of universal functions (ufuncs) that operate element-wise on ndarrays.

In [17]:
# Square
array1 = np.array([3, 4, 5, 6])
sqr_arr = np.square(array1)
print("sqr_arr", sqr_arr)

# Square root
a = np.array([9, 16, 512])
sqrt_arr = np.sqrt(a)
print("sqrt_arr", sqrt_arr)

# Exponential
exp_arr = np.exp(a)
print("exp_arr", exp_arr)

# Sum of all elements
sum_elements = np.sum(a)
print("sum_elements", sum_elements)

# Transpose of Array
# using In-built function 'T'
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
Trans_arr = arr1.T
print("\nTranspose of Array: ")
print(Trans_arr)

sqr_arr [ 9 16 25 36]
sqrt_arr [ 3.        4.       22.627417]
exp_arr [8.10308393e+003 8.88611052e+006 2.28441359e+222]
sum_elements 537

Transpose of Array: 
[[4. 2.]
 [7. 6.]]


### Indexing and Slicing:
#### You can access elements of ndarrays using indexing and slicing, similar to Python lists.

In [11]:
arr = np.array([10, 20, 30, 40, 50])

# Accessing individual element
print(arr[2])  # Outputs: 30

# Slicing
print(arr[1:4])  # Outputs: [20, 30, 40]


30
[20 30 40]


In [12]:
# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)


Array created using passed tuple:
 [1 3 2]


In [13]:
# Integer datatype
# guessed by Numpy
x = np.array([1, 2])  
print("Integer Datatype: ")
print(x.dtype)         
 
# Float datatype
# guessed by Numpy
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype)  
 
# Forced Datatype
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)

Integer Datatype: 
int32

Float Datatype: 
float64

Forcing a Datatype: 
int64


### shape:
#### The shape attribute of a NumPy ndarray returns a tuple representing the dimensions of the array. It tells you the number of elements along each axis (dimension) of the array.

In [1]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Outputs: (2, 3)


(2, 3)


### reshape:
#### The reshape function allows you to change the shape (dimensions) of an existing ndarray without changing the data it contains. It returns a new ndarray with the specified shape.

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.shape)
reshaped_arr = arr.reshape(4, 2)  # Reshape to a 2x3 matrix
print(reshaped_arr.shape)
print(reshaped_arr)


(8,)
(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### If you want to reshape an array and automatically infer one of the dimensions based on the other, you can use the special value -1:

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6]) # 1D 
reshaped_arr = arr.reshape(2, -1)  # Reshape to a 2xN matrix (N is inferred)
print(reshaped_arr)
print()
reshaped_arr = arr.reshape(-1)  # Reshape to a 2xN matrix (N is inferred)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


### Conditions and Boolean arrays
#### In NumPy, you can use conditions and boolean arrays to perform element-wise comparisons and create boolean arrays that represent the truth values of these comparisons. 
#### Boolean arrays are particularly useful for indexing and selecting elements from ndarrays based on certain conditions.

In [8]:
arr = np.array([1, 0, 1, 0, 0, 1, 0])
  
print(f'Original Array: {arr}')
  
bool_arr = np.array(arr, dtype='bool')
  
print(f'Boolean Array: {bool_arr}')

Original Array: [1 0 1 0 0 1 0]
Boolean Array: [ True False  True False False  True False]


In [9]:
arr = np.array([5, None, 1, 25, -10, 0, 'A'])

print(f'Original Array: {arr}')

bool_arr = np.array(arr, dtype='bool')

print(f'Boolean Array: {bool_arr}')


Original Array: [5 None 1 25 -10 0 'A']
Boolean Array: [ True False  True  True  True False  True]


In [4]:
arr = np.array([1, 2, 3, 4, 5])

# Element-wise comparisons
greater_than_3 = arr > 3
less_than_equal_2 = arr <= 2
equal_to_4 = arr == 4

print(greater_than_3)       # [False False False  True  True]
print(less_than_equal_2)    # [ True  True False False False]
print(equal_to_4)           # [False False False  True False]

[False False False  True  True]
[ True  True False False False]
[False False False  True False]


### Boolean Indexing:
#### Boolean arrays can be used for indexing to select elements that satisfy certain conditions. When a boolean array is used as an index for an ndarray, only the elements corresponding to True values are selected.

In [5]:
selected_elements = arr[greater_than_3]
print(selected_elements)  # [4 5]


[4 5]


### Combining Conditions:
#### You can combine conditions using logical operators (& for element-wise "and", | for element-wise "or", and ~ for element-wise "not") to create complex conditions.

In [6]:
combined_condition = (arr > 2) & (arr < 5)
print(combined_condition)  # [False False  True  True False]


[False False  True  True False]


### Using Boolean Arrays for Assignment:
#### Boolean arrays can also be used to selectively modify elements of an ndarray.

In [7]:
arr[arr > 3] = 0
print(arr)  # [1 2 3 0 0]
    

[1 2 3 0 0]
